/* Database schema to keep the structure of entire database. */

CREATE TABLE animals(
id INT GENERATED BY DEFAULT AS IDENTITY,
name VARCHAR(250),
date_of_birth DATE,
escape_attempts INT,
neutered BOOLEAN,
weight_kg FLOAT,
species VARCHAR (50)
);

CREATE TABLE owners (
id SERIAL PRIMARY KEY,
 full_name VARCHAR(255)
 age INT
  );

CREATE TABLE species (
id SERIAL PRIMARY KEY,
 name VARCHAR(255)
  );

ALTER TABLE animals ADD PRIMARY KEY(id);
ALTER TABLE animals DROP COLUMN species;

ALTER TABLE animals ADD COLUMN species_id INT REFERENCES species(id);
ALTER TABLE animals ADD COLUMN owner_id INT REFERENCES owners(id);